/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WorkflowsIndexRouteImport } from './routes/workflows/index'
import { Route as SubjectsIndexRouteImport } from './routes/subjects/index'
import { Route as SchemasIndexRouteImport } from './routes/schemas/index'
import { Route as EventsIndexRouteImport } from './routes/events/index'
import { Route as VerifySubjectIdRouteImport } from './routes/verify/$subjectId'
import { Route as EventsCreateRouteImport } from './routes/events/create'
import { Route as AdminRolesIndexRouteImport } from './routes/admin/roles/index'
import { Route as AdminPermissionsIndexRouteImport } from './routes/admin/permissions/index'
import { Route as EventsSubjectSubjectIdRouteImport } from './routes/events/subject.$subjectId'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkflowsIndexRoute = WorkflowsIndexRouteImport.update({
  id: '/workflows/',
  path: '/workflows/',
  getParentRoute: () => rootRouteImport,
} as any)
const SubjectsIndexRoute = SubjectsIndexRouteImport.update({
  id: '/subjects/',
  path: '/subjects/',
  getParentRoute: () => rootRouteImport,
} as any)
const SchemasIndexRoute = SchemasIndexRouteImport.update({
  id: '/schemas/',
  path: '/schemas/',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsIndexRoute = EventsIndexRouteImport.update({
  id: '/events/',
  path: '/events/',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifySubjectIdRoute = VerifySubjectIdRouteImport.update({
  id: '/verify/$subjectId',
  path: '/verify/$subjectId',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsCreateRoute = EventsCreateRouteImport.update({
  id: '/events/create',
  path: '/events/create',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRolesIndexRoute = AdminRolesIndexRouteImport.update({
  id: '/admin/roles/',
  path: '/admin/roles/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPermissionsIndexRoute = AdminPermissionsIndexRouteImport.update({
  id: '/admin/permissions/',
  path: '/admin/permissions/',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsSubjectSubjectIdRoute = EventsSubjectSubjectIdRouteImport.update({
  id: '/events/subject/$subjectId',
  path: '/events/subject/$subjectId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/events/create': typeof EventsCreateRoute
  '/verify/$subjectId': typeof VerifySubjectIdRoute
  '/events': typeof EventsIndexRoute
  '/schemas': typeof SchemasIndexRoute
  '/subjects': typeof SubjectsIndexRoute
  '/workflows': typeof WorkflowsIndexRoute
  '/events/subject/$subjectId': typeof EventsSubjectSubjectIdRoute
  '/admin/permissions': typeof AdminPermissionsIndexRoute
  '/admin/roles': typeof AdminRolesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/events/create': typeof EventsCreateRoute
  '/verify/$subjectId': typeof VerifySubjectIdRoute
  '/events': typeof EventsIndexRoute
  '/schemas': typeof SchemasIndexRoute
  '/subjects': typeof SubjectsIndexRoute
  '/workflows': typeof WorkflowsIndexRoute
  '/events/subject/$subjectId': typeof EventsSubjectSubjectIdRoute
  '/admin/permissions': typeof AdminPermissionsIndexRoute
  '/admin/roles': typeof AdminRolesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/events/create': typeof EventsCreateRoute
  '/verify/$subjectId': typeof VerifySubjectIdRoute
  '/events/': typeof EventsIndexRoute
  '/schemas/': typeof SchemasIndexRoute
  '/subjects/': typeof SubjectsIndexRoute
  '/workflows/': typeof WorkflowsIndexRoute
  '/events/subject/$subjectId': typeof EventsSubjectSubjectIdRoute
  '/admin/permissions/': typeof AdminPermissionsIndexRoute
  '/admin/roles/': typeof AdminRolesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/register'
    | '/events/create'
    | '/verify/$subjectId'
    | '/events'
    | '/schemas'
    | '/subjects'
    | '/workflows'
    | '/events/subject/$subjectId'
    | '/admin/permissions'
    | '/admin/roles'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/register'
    | '/events/create'
    | '/verify/$subjectId'
    | '/events'
    | '/schemas'
    | '/subjects'
    | '/workflows'
    | '/events/subject/$subjectId'
    | '/admin/permissions'
    | '/admin/roles'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/register'
    | '/events/create'
    | '/verify/$subjectId'
    | '/events/'
    | '/schemas/'
    | '/subjects/'
    | '/workflows/'
    | '/events/subject/$subjectId'
    | '/admin/permissions/'
    | '/admin/roles/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  EventsCreateRoute: typeof EventsCreateRoute
  VerifySubjectIdRoute: typeof VerifySubjectIdRoute
  EventsIndexRoute: typeof EventsIndexRoute
  SchemasIndexRoute: typeof SchemasIndexRoute
  SubjectsIndexRoute: typeof SubjectsIndexRoute
  WorkflowsIndexRoute: typeof WorkflowsIndexRoute
  EventsSubjectSubjectIdRoute: typeof EventsSubjectSubjectIdRoute
  AdminPermissionsIndexRoute: typeof AdminPermissionsIndexRoute
  AdminRolesIndexRoute: typeof AdminRolesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workflows/': {
      id: '/workflows/'
      path: '/workflows'
      fullPath: '/workflows'
      preLoaderRoute: typeof WorkflowsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subjects/': {
      id: '/subjects/'
      path: '/subjects'
      fullPath: '/subjects'
      preLoaderRoute: typeof SubjectsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/schemas/': {
      id: '/schemas/'
      path: '/schemas'
      fullPath: '/schemas'
      preLoaderRoute: typeof SchemasIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/': {
      id: '/events/'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify/$subjectId': {
      id: '/verify/$subjectId'
      path: '/verify/$subjectId'
      fullPath: '/verify/$subjectId'
      preLoaderRoute: typeof VerifySubjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/create': {
      id: '/events/create'
      path: '/events/create'
      fullPath: '/events/create'
      preLoaderRoute: typeof EventsCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/roles/': {
      id: '/admin/roles/'
      path: '/admin/roles'
      fullPath: '/admin/roles'
      preLoaderRoute: typeof AdminRolesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/permissions/': {
      id: '/admin/permissions/'
      path: '/admin/permissions'
      fullPath: '/admin/permissions'
      preLoaderRoute: typeof AdminPermissionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/subject/$subjectId': {
      id: '/events/subject/$subjectId'
      path: '/events/subject/$subjectId'
      fullPath: '/events/subject/$subjectId'
      preLoaderRoute: typeof EventsSubjectSubjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  EventsCreateRoute: EventsCreateRoute,
  VerifySubjectIdRoute: VerifySubjectIdRoute,
  EventsIndexRoute: EventsIndexRoute,
  SchemasIndexRoute: SchemasIndexRoute,
  SubjectsIndexRoute: SubjectsIndexRoute,
  WorkflowsIndexRoute: WorkflowsIndexRoute,
  EventsSubjectSubjectIdRoute: EventsSubjectSubjectIdRoute,
  AdminPermissionsIndexRoute: AdminPermissionsIndexRoute,
  AdminRolesIndexRoute: AdminRolesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
